ci:
  skip: [stylua-alias]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
    -   id: stylua
        alias: stylua-alias
