repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace  # hi again
-   repo: local
    hooks:
    -   id: hello
        name: hello
        language: golang
        additional_dependencies: ['golang.org/x/example/hello@latest']
        entry: hello
        pass_filenames: false
        verbose: true
        always_run: true
-   repo: local
    hooks:
    -   id: also-bad
        name: plz no do
        entry: flake8 --version
        language: python
        additional_dependencies: [flake8]
        verbose: true
        always_run: true
        language_version: python3.11
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.30.0
    hooks:
    -   id: eslint
        args: [--fix]
-   repo: https://github.com/shssoichiro/oxipng
    rev: v8.0.0
    hooks:
    -   id: oxipng
