repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: rust-local
        name: rust-local
        language: rust
        entry: shellharden
        types: [shell]
        additional_dependencies: [cli:shellharden:3.1.0]
    -   id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: rust
        types: [rust]
        additional_dependencies: [cli:rustfmt-nightly:1.4.21, smallvec:0.5.1]
