repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/biomejs/pre-commit
    rev: v0.5.0
    hooks:
    -   id: biome-check
        additional_dependencies: ["@biomejs/biome@1.8.1"]
