repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        additional_dependencies: [astpretty, cfgv]
    -   id: end-of-file-fixer
        additional_dependencies: [cfgv, astpretty]
