repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: hello
        name: hello
        language: golang
        additional_dependencies: ['golang.org/x/example/hello@latest']
        entry: hello
        pass_filenames: false
        verbose: true
        always_run: true

